---
title: "Plots and p-values for the main paper"
output: pdf_document
---

```{r setup, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(knitr)
library(here)
library(readxl)

library(cowplot) #Optional, can be commented out
theme_set(cowplot::theme_cowplot())

temp_dir <- "local_temp_data"
if(!dir.exists(temp_dir)) {
  dir.create(temp_dir)
}
```

```{r}
animals_levels_raw <- c("mouse","cow","pig")
animals_labels <- c("Mouse","Bovine","Porcine")
```


```{r}
base_plot <- function(data, x, y, y_expand = c(0, 1.65)) {
  # The large_point version
  mean_in_color = TRUE
  line_size = 1
  point_size = 2.25

  # THe small_points version
  # mean_in_color = FALSE
  # line_size = 1
  # point_size = 1.5
  
  x <- enquo(x)
  y <- enquo(y)
  
  if(mean_in_color) {
    mean_summary <- stat_summary(geom = "errorbar", fun.y = "mean", aes(ymax = ..y.., ymin = ..y..), size = line_size)
  } else {
    mean_summary <- stat_summary(geom = "errorbar", fun.y = "mean", aes(ymax = ..y.., ymin = ..y..), color = "black", size = line_size)
  }

  y_breaks <- seq(0, max(pull(data,!!y) + 1.999), by = 0.2)
  
  ggplot(data, aes(x = !!x, y = !!y, color = !!x, fill = !!x, shape = !!x)) +
    stat_summary(geom = "bar", fun.data = "mean_se", width = 0.9, color = NA) +
    stat_summary(geom = "errorbar", fun.data = "mean_se", width = 0.5, size = line_size) +
    mean_summary +
    geom_point(position = position_jitter(width = 0.35, height = 0), size = point_size) +
    scale_color_manual(values = c("#0077ff", "#ff0000", "#505050")) +
    scale_fill_manual(values = c("#d8eaff", "#ffd8d8", "#e5e5e5")) +
    theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.ticks.x = element_blank()) +
    guides(color = guide_legend(override.aes = list(alpha = 1, linetype = 0, fill = NA))) + 
    expand_limits(y = y_expand) + scale_y_continuous(expand = expand_scale(mult = c(0, .05)), breaks = y_breaks)
}

plots <- list()
widths <- list()
```

```{r}
compute_p_values_single <- function(data, g, method_sufffix = "") {
  data_animal <- data %>% filter(group == g)
  res <- list()
  nextItem <- 1
  
  perfect <- data_animal %>% filter(Reporter == "1x-perfect") %>% pull(response)
  bulged <- data_animal %>% filter(Reporter == "4x-bulged") %>% pull(response)
  mutant <- data_animal %>% filter(Reporter == "4x-mutant") %>% pull(response)
  res[[nextItem]] <- data.frame(group = g, Method = paste0("t-test", method_sufffix), 
                                  p_perfect_mutant = t.test(perfect, mutant,var.equal = FALSE)$p.value,
                                  p_bulged_mutant = t.test(bulged, mutant,var.equal = FALSE)$p.value)
  nextItem <- nextItem + 1
  res[[nextItem]] <- data.frame(group = g, Method = paste0("t-test - equal variance", method_sufffix), 
                                p_perfect_mutant = t.test(perfect, mutant,var.equal = TRUE)$p.value,
                                p_bulged_mutant = t.test(bulged, mutant,var.equal = TRUE)$p.value)
  nextItem <- nextItem + 1
  tukey_res <- TukeyHSD(aov(lm(response ~ Reporter, data_animal)))$Reporter

  res[[nextItem]] <- data.frame(group = g, Method = paste0("TukeyHSD", method_sufffix), 
                                p_perfect_mutant = tukey_res["4x-mutant-1x-perfect", "p adj"],
                                p_bulged_mutant = tukey_res["4x-mutant-4x-bulged", "p adj"])
  nextItem <- nextItem + 1
  
  do.call(rbind, res)
}

compute_p_values <- function(data, response = `Relative nanoluc activity`, group = Animal) {
  res <- list()
  data <- data %>% mutate(response = {{ response }}, group = {{ group }})
  nextItem <- 1
  for(g in unique(data$group)) {
    res[[nextItem]] <- compute_p_values_single(data, g)
    nextItem <- nextItem + 1
    res[[nextItem]] <- compute_p_values_single(data %>% mutate(response = log(response)), g, " - log")
    nextItem <- nextItem + 1
  }
  
  do.call(rbind, res)
}


summarise_p_values <- function(data, response = `Relative nanoluc activity`, group = Animal) {
compute_p_values(data, {{ response }}, {{group }}) %>% group_by(group) %>% 
  summarise(min_p_p_perfect_mutant = min(p_perfect_mutant), max_p_perfect_mutant = max(p_perfect_mutant), 
            min_p_bulged_mutant = min(p_bulged_mutant), max_p_bulged_mutant = max(p_bulged_mutant)) %>%
  knitr::kable()
}

```

### Nanoluc-20 hours-mammals

Fig 2D
```{r, fig.height=3, fig.width=6}
luciferase_file <- here("private_data", "190603 for martin.xlsx")
luciferase_data <-  read_excel(luciferase_file, sheet = "Nanoluc-20 hours-mammals", range = "A2:B100", col_names = c("Condition", "Activity"))

luciferase_data <- luciferase_data %>%
  filter(Condition != "") %>%
  separate(Condition, into = c("Animal_raw", "Binding"), sep = " ") %>%
  mutate(Animal = factor(Animal_raw, levels = animals_levels_raw, labels = animals_labels))


plots$luciferase <- luciferase_data %>%
  base_plot(Binding, Activity) +
  facet_wrap(~Animal)


plots$luciferase
```

```{r}
summarise_p_values(luciferase_data %>% mutate(Reporter = Binding), Activity)
```

### miR-30c mammals

Fig S2 C

```{r, fig.height=3, fig.width=6}
combined_file <- here("private_data", "200115 for martin.xlsx")
miR30c_data <- read_excel(combined_file, sheet = "miR-30c mammals") %>% 
  mutate(Animal = factor(Animal, levels = animals_labels))
plots$miR30c <- base_plot(miR30c_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
plots$miR30c
```

```{r}
summarise_p_values(miR30c_data)
```

### Let-7a porcine 40hours

Fig 2E

```{r, fig.height = 3, fig.width = 3.5}
let7a_porcine_data <- read_excel(combined_file, sheet = "Let-7a porcine 40hours", col_names = c("Animal","Reporter","Relative nanoluc activity"), range = "A1:C10")
plots$let7a_porcine <- base_plot(let7a_porcine_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$let7a_porcine <- 3.5
plots$let7a_porcine
```

```{r}
summarise_p_values(let7a_porcine_data)
```

### Let-7a and miR-30c 3t3

Fig S2B

```{r, fig.height=3, fig.width=5}
let7_miR_3t3_data <- read_excel(combined_file, sheet = "Let-7a and miR-30c 3t3")
plots$let7_miR_3t3 <- base_plot(let7_miR_3t3_data, Reporter, `Relative nanoluc activity`) +
  facet_wrap(~miRNA)
widths$let7_miR_3t3 <- 5

plots$let7_miR_3t3
```

```{r}
summarise_p_values(let7_miR_3t3_data, group = miRNA)
```


### porcine mimics

Fig. 3B

```{r, fig.height=3, fig.width=6}
number_mimic_levels <- c("500k","250k", "100k")
porcine_mimics_data <- read_excel(combined_file, sheet = "porcine mimics") %>%
  mutate(number_mimic = factor(`number of mimic molecules`, levels = number_mimic_levels))
plots$porcine_mimics <- base_plot(porcine_mimics_data, Reporter, `Relative nanoluc activity`) +
  facet_wrap(~number_mimic)

plots$porcine_mimics
```

```{r}
summarise_p_values(porcine_mimics_data, group = number_mimic)
```

### mouse mimics
Fig 3A

```{r, fig.height=3, fig.width=6}
number_mimic_levels <- c("500k","250k", "100k")
mouse_mimics_data <- read_excel(combined_file, sheet = "mouse mimics") %>%
  mutate(number_mimic = factor(`number of mimic molecules`, levels = number_mimic_levels))
plots$mouse_mimics <- base_plot(mouse_mimics_data, Reporter, `Relative nanoluc activity`) +
  facet_wrap(~number_mimic)

plots$mouse_mimics
```

```{r}
summarise_p_values(mouse_mimics_data, group = number_mimic)
```

### Growing oocytes (mouse)


```{r, fig.height = 3, fig.width = 3.5}
growing_oocytes_data <- read_excel(combined_file, sheet = "Growing oocytes (mouse)", col_names = c("Animal","Reporter","Relative nanoluc activity"), range = "A1:C10")
plots$growing_oocytes <- base_plot(growing_oocytes_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$growing_oocytes <- 3.5
plots$growing_oocytes
```

```{r}
summarise_p_values(growing_oocytes_data)
```

### mouse 100k NL

```{r, fig.height = 3, fig.width = 3.5}
mouse_100k_NL_data <- read_excel(combined_file, sheet = "mouse 100k NL")
plots$mouse_100k_NL <- base_plot(mouse_100k_NL_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$mouse_100k_NL <- 3.5
plots$mouse_100k_NL
```

```{r}
summarise_p_values(mouse_100k_NL_data)
```

### mouse 100k NL+250k mimic

```{r, fig.height = 3, fig.width = 3.5}
mouse_100k_NL_mimic_data <- read_excel(combined_file, sheet = "mouse 100k NL+250k mimic")
plots$mouse_100k_NL_mimic <- base_plot(mouse_100k_NL_mimic_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$mouse_100k_NL_mimic <- 3.5
plots$mouse_100k_NL_mimic
```

```{r}
summarise_p_values(mouse_100k_NL_mimic_data)
```

### Let7a mouse(combined)

```{r, fig.height = 3, fig.width = 3.5}
let7_mouse_combined_data <- read_excel(combined_file, sheet = "Let7a mouse(combined)")
plots$let7_mouse_combined <- base_plot(let7_mouse_combined_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$let7_mouse_combined <- 3.5
plots$let7_mouse_combined
```

```{r}
summarise_p_values(let7_mouse_combined_data)
```

### Let7a mouse(femto)

```{r, fig.height = 3, fig.width = 3.5}
let7_mouse_femto_data <- read_excel(combined_file, sheet = "Let7a mouse(femto)")
plots$let7_mouse_femto <- base_plot(let7_mouse_femto_data, Reporter, `Relative nanoluc activity`) + facet_wrap(~Animal)
widths$let7_mouse_femto <- 3.5
plots$let7_mouse_femto
```

```{r}
summarise_p_values(let7_mouse_femto_data)
```


```{r}
three_groups_width = 6
base_height = 3
for(type in c(".png",".wmf")) {
  for(plot_name in names(plots)) {
    if(!is.null(widths[[plot_name]])) {
      width = widths[[plot_name]]
    } else {
      width = three_groups_width
    }
    ggsave(paste0(temp_dir,"/", plot_name, type), plots[[plot_name]], width = width, height = base_height)
  }
}

```

