---
title: "miRNA and siRNA modelling"
output: html_notebook
---


```{r setup}
library(deSolve)
library(tidyverse)
```

Using nM as unit, K_m and k_cat from Zamore 2015.
AGO abundance (E_0) from Wang et al. 2012 Quantitative functions of Argonaute
proteins in mammalian development

cell radius / volume guessed

```{r}
nanomole <- 6.022e14

params_miRNA_base <- c(
  K_M = 1.7,
  k_cat = 7.8e-2,
  k_on = 3.9e8,
  E_0_amount = 1.7e5 / nanomole)

params_siRNA_base <- params_miRNA_base
params_siRNA_base["k_cat"] <- params_siRNA_base["k_cat"] * 5

params_miRNA_base["k_off"] <- params_miRNA_base["K_M"] * params_miRNA_base["k_on"] - params_miRNA_base["k_cat"]
params_siRNA_base["k_off"] <- params_miRNA_base["K_M"] * params_miRNA_base["k_on"] - params_miRNA_base["k_cat"]

RNA_count_normal <- 5000
cell_radius <- 10e-6 
cell_volume <- (4/3)*pi* cell_radius^3

RNA_count_oocyte <- 5e5
oocyte_radius <- 80e-6 
oocyte_volume <- (4/3)*pi* oocyte_radius^3

times <- seq(0,10, length.out = 100)

```


```{r}


mm_cleaveage <- function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    V_max <- k_cat * (E_0_amount / cell_volume)
    rate_product <- (V_max * target) / (K_M + target)
    list(-rate_product)
  })
}


params_miRNA <- params_miRNA_base
params_miRNA["cell_volume"] <- cell_volume

params_siRNA <- params_siRNA_base
params_siRNA["cell_volume"] <- cell_volume

state <- c(target = RNA_count_normal / (nanomole * cell_volume))

out.miRNA <- ode(y = state, times = times, func = mm_cleaveage, parms = params_miRNA)
out.siRNA <- ode(y = state, times = times, func = mm_cleaveage, parms = params_siRNA)

out.miRNA %>% as.data.frame() %>% rename(target.miRNA = target) %>% mutate(target.siRNA = out.siRNA[,"target"]) %>% gather("type", "value", -time) %>% ggplot(aes(x = time, y = value, color = type)) + geom_line() + ggtitle(paste0("Init count = ", RNA_count_normal, " cell volume: ", cell_volume))


params_miRNA <- params_miRNA_base
params_miRNA["cell_volume"] <- oocyte_volume

params_siRNA <- params_siRNA_base
params_siRNA["cell_volume"] <- oocyte_volume

state <- c(target = RNA_count_oocyte / (nanomole * oocyte_volume))

out.miRNA.oo <- ode(y = state, times = times, func = mm_cleaveage, parms = params_miRNA)
out.siRNA.oo <- ode(y = state, times = times, func = mm_cleaveage, parms = params_siRNA)

out.miRNA.oo %>% as.data.frame() %>% rename(target.miRNA = target) %>% mutate(target.siRNA = out.siRNA.oo[,"target"]) %>% gather("type", "value", -time) %>% ggplot(aes(x = time, y = value, color = type)) + geom_line() + ggtitle(paste0("Init count = ", RNA_count_oocyte, ", cell volume: ", oocyte_volume))

```

```{r}
synthesis <- 0

cleaveage_synthesis <- function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    enzyme <- -k_on * enzyme * target + k_off * complex + k_cat * complex
    target <- -k_on * enzyme * target + k_off * complex +                  (synthesis / cell_volume)
    complex <- k_on * enzyme * target - k_off * complex - k_cat * complex
    list(c(target, enzyme, complex))
  })
}

params_miRNA <- params_miRNA_base
params_miRNA["cell_volume"] <- cell_volume
params_miRNA["synthesis"] <- synthesis

params_siRNA <- params_siRNA_base
params_siRNA["cell_volume"] <- cell_volume
params_siRNA["synthesis"] <- synthesis

state <- c(target = RNA_count_normal / (nanomole * oocyte_volume), enzyme = params_miRNA["E_0_amount"] / params_miRNA["cell_volume"], complex = 0)

out.miRNA <- ode(y = state, times = times, func = cleaveage_synthesis, parms = params_miRNA)
out.siRNA <- ode(y = state, times = times, func = cleaveage_synthesis, parms = params_siRNA)

out.miRNA %>% as.data.frame() %>% rename(target.miRNA = target) %>% mutate(target.siRNA = out.siRNA[,"target"]) %>% gather("type", "value", -time) %>% ggplot(aes(x = time, y = value, color = type)) + geom_line() + ggtitle(paste0("Init count = ", RNA_count_normal, " cell volume: ", cell_volume))


```

